### ISSUE TITLE
Översättning av dcat:contactPoint

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#13]
dcat:contactPoint kallas rätt och slätt "kontakt" på Öppnadata.se för tillfället.
Riksarkivet/SIS föreslog "kontaktuppgift". Kontaktpunkt låter inte som korrekt svenska.

**Comment by mattiasekhem** [comment]
Både kontaktpunkt och kontaktuppgift finns med i SAOL. Eftersom kontaktuppgift finns föreslaget och är brett använt som begrepp föreslår jag att vi i DCAT-AP-SE använder kontaktuppgift.
