### ISSUE TITLE
Stöd för att ladda multipla kataloger för en organisation

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#14]
Se förslag här:
https://metasolutionsab.github.io/DCAT-AP-SE/docs/harvesting.html#multipla-kataloger-per-organisation

**Comment by kristineulander** [comment]
Tolkar jag det rätt att då kan t.ex olika avdelningar från samma organisation ladda upp "egna" kataloger inom ramen för sin organisation? Lyft gärna upp ett par exempel för att ge sammanhanget/syftet

**Comment by matthiaspalmer** [comment]
@kristineulander Ja precis, lösningen kommer fungera oberoende om sådana subkataloger motsvarar olika system eller olika organisatoriska indelningar.

Här är ett förslag på exempel som kan läggas in i dokumentationen om det passar:

Länsstyrelserna har en huvudkatalog som pekar ut 23 underkataloger:

1. 21 länsstyrelsespecifika kataloger, dvs en för Halland, en för Västra götaland osv.
2. 1 katalog med gemensama datamängder som inte hör till någon enskild länsstyrelse.
3. 1 katalog med alla geodatamängder som förvaltas centralt i ett separat system.

**Comment by carwash** [comment]
Det här är också relevant för oss på Riksantikvarieämbetet. Idag levererar vi K-samsöks- (dvs aggregerad) och icke-K-samsöksdata, där vissa datamängder förekommer hos bägge två på olika format. Den uppdelningen känns inte supertydlig.

**Comment by AlexReutman** [comment]
Hej @matthiaspalmer - länken till förslaget fungerar inte längre - har du möjlighet att skicka ny länk? Har behov av att kika på ett exempel gällande detta. Tack på förhand.

**Comment by mattiasaxell** [comment]
@AlexReutman Förslaget var på en gammal staging-sida innan dokumentationen lanserats. Sedan några år tillbaka finns dokumentationen  som ersatt den på https://docs.dataportal.se/ och är 100% sökbar! :grin: 

Det går t.ex. att skriva "multipla" i sökrutan för att nå till dokumentationen du söker efter specifikt: https://docs.dataportal.se/dcat/docs/harvesting/#multipla-kataloger-per-organisation :blush:

**Comment by AlexReutman** [comment]
@mattiasaxell tack för ditt svar! Japp, det var genom den sökbara dokumentationen på dataportal.se som jag hittade till denna "issue" var jag hoppades kunna hitta ett exempel i form av en/flera rdf-filer. Finns inget sådant exempel?

**Comment by mattiasaxell** [comment]
@AlexReutman Jag känner personligen inte till exempel på ihopslagna RDF-filer men det finns verktyg för det här som kanske kan hjälpa dig: https://sandbox.admin.dataportal.se/toolkit/catalog - kan du återkomma om det är till hjälp eller ej?
