### ISSUE TITLE
Obligatorisk dct:publisher på datamängden

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#16]
DCAT-AP säger att dct:publisher är rekommenderad.

Det vore bra att göra den obligatorisk, särskilt då den är en väldigt viktigt instrument för filtrering på öppnadata.se och också på Europeiska Dataportalen (EDP).
När datamängder skördas till EDP så slås alla Svenska datamängder ihop till en stor katalog. Då det inte finns något arv av egenskaper från katalognivån till datamängden gäller det att vara noga att uttrycka information som behövs på datamängden.
Mer specifikt, om man inte uttrycker dct:publisher för varje datamängd kommer man inte på EDP  
se varifrån datamängden kommer.

Notera att detta också stämmer med hur W3C talar om en katalog, dvs. som en collection av datamängder och distributioner.

**Comment by carwash** [comment]
Instämmer; viktigt att kunna skilja mellan olika utgivare, särskilt utifrån perspektivet aggregator.
