### ISSUE TITLE
Behov av Contactpoint på katalognivån

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#2]
I DCAT-AP1.1 finns det inte stöd för detta, men i nya W3C DCAT 2 har man ändrat så Catalog är en subklass till datamängd varav contactpoint får användas där.

I riksarkivets DCAT spec från 2018-06-20 finns denna angiven som obligatorisk.
Argumentet då var (om jag inte missminner mig) att katalogen är en PSI-förteckning enligt lagen som man behöver ha en kontaktpunkt till. Notera dock att i registrera.oppnadata.se är varje katalog registrerad av en användare, denna användare är en slags kontaktpunkt ur skördningsperspektiv.

Frågan är vem som behöver kontaktpunkten, är det en allmänhet som enligt lag vill ställa frågor om PSI-förteckningen eller är det skördningsansvarig för öppnadata.se, i det senare fallet räcker användarhanteringen på registrera.

Man bör också väga fördelar mot nackdelar här med situationen att en dataleverantör behöver ange kontaktpunkt och publisher i DCAT-AP uttrycket och därefter ha en användare på registrera, i de flesta fall motsvarar alla tre samma entitet.

Om contactPoint ska finnas på katalogen så bör det finnas tydliga exempel när det inte är samma som publisher och behovet är för allmänheten och inte internt på öppnadata.se

**Comment by philiplevin** [comment]
Jag har grävt lite i detta och landat i följande. 

Av den aktuella bestämmelsen i lagen (2010:566) om vidareutnyttjande av handlingar från den offentliga förvaltningen (11 § andra stycket) framgår inget krav på kontaktperson. Inte heller i 15 § arkivförordningen, där föreskriftsrätten framgår. Frågan berörs dock kortfattat i förarbetena avseende ändringarna i lagen. 

Förarbeten

I SOU 2014:10 hänvisar man till E-delegationens vägledning om vidareutnyttjande av offentliga information och konstaterar att rekommendationerna i den är lämpligast att använda som utgångspunkt för att bestämma vilken information förteckningarna ska innehålla. Där framgår bland annat ”eventuell särskild kontaktperson för den aktuella informationsresursen”. (sidorna 91 och 169 i SOU:n)

Liknande skrivningar återfinns i efterföljande proposition (prop. 2014/15:79) där regeringen konstaterar att förteckningarna bör innehålla ”exempelvis namnet på och en kort beskrivning av informationsresursen, uppgifter om den senaste uppdateringen och befintliga tekniska format, samt information om avgifter, andra eventuella villkor, kända begränsningar och _eventuell särskild kontaktperson för den aktuella informationsresursen_ (egen kursivering).” (sida. 29)

Riksarkivets förstudie

Riksarkivet konstaterar i sin förstudie om PSI-förteckningar att ”en del andra saker, som behov av att ha "kontakt" (i form av person/funktion) och "villkor för vidareutnyttjande" ansågs också viktiga som obligatoriska fält, eftersom de syftar till att förtydliga hur data får användas för vidareutnyttjande och bistå enskilda i kontakterna med berörd myndighet.” (sida 19)

Jag hittar emellertid inte någon ytterligare information som beskriver behovet ytterligare eller motiverar kravet. Men jag utgår från att det har framkommit inom ramen för arbetet med förstudien. Jag hittar heller inget utförligt resonemang om behovet i Riksarkivets slutrapport om regeringsuppdraget att främja statliga myndigheters arbete med att tillgängliggöra data för vidareutnyttjande från juni 2018.

Bedömning

Min bedömning är att det inte finns något uttryckligt krav på att förteckningen måste innehålla information avseende kontaktperson. Den slutsatsen drar jag i och med att det i förarbetena dels står ”bör”, alternativt ”som exempel” samt att det står ”eventuell särskild kontaktperson”. Däremot verkar både lagstiftaren och Riksarkivet vara av uppfattningen att det kan vara värdefull information att ha i förteckningen. Om vi anser att kontaktperson inte ska finnas med i förteckningen bör vi, mot bakgrund av vad som framförs ovan, kunna motivera varför vi anser att informationen inte är nödvändig. Jag tolkar skrivningen i förstudien som att information en första hand är avsedd för enskilda i kontakterna med berörd myndighet.

**Comment by matthiaspalmer** [comment]
Tack för ditt inlägg Philip.

En kommentar är att en PSI-förteckning är att jämföra med en katalog i DCAT terminologin. Det som är mest intressant i katalogen / förteckningen är dess innehåll, dvs datamängderna. Datamängderna kan jämföras med "informationsresurs". Tänk t.ex. att en kommun har två datamängder,  luftkvalité och leverantörreskontra. Att ange en kontaktpunkt för datamängden luftkvalité och eventuellt en annan för leverantörsreskontra är en sak (och högst rimligt). Att ange en kontaktpunkt för hela förteckningen är en annan sak.

Om jag förstår skrivningen ovan är det snarare kontaktpunkt på datamängden/informationsresursen som är relevant att ha, det är viktigt att få rätt ingång för att kunna ställa kompletterande frågor kring kvalite, åtkomst, format etc. om det inte är tydligt nog. Att tillhandahålla en kontaktpunkt på katalogen som helhet motsvara ett annat behov.

En möjligt behov skulle vara att stödja allmänheten i hur de ska skicka "begäran om vidareutnyttjande" för datamängder/informationsresurser som ännu inte är listade i förteckningen. Huruvida detta är något som måste stödjas är oklart utifrån lagtexten. Att skicka begäran kring de datamängder som redan finns i förteckningen är ju redan löst med kontaktpunkten där.
