### ISSUE TITLE
3.1.11 Språk - bara vissa språk

### ISSUE THREAD

**Issue by bjornhagstrom** [MetaSolutionsAB/DCAT-AP-SE#28]
3.1.11 Språk har ett antal språk listade men det finns ju fler än dessa. Detta bör kanske framgå?

**Comment by matthiaspalmer** [comment]
De språk som är listade är de som [listas av publication office](https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/language).
Det är DCAT-AP som pekar på den listan. Jag kopierade listan för några år sedan, så det kanske är dags att kolla om det tillkommit några.

**Comment by bjornhagstrom** [comment]
Ok så man kan inte publicera data på andra språk än de utvalda (och samtidigt beskriva den med korrekt metadata)? Konstig lösning. Kanske vore bra att försöka få till en annan lösning framöver?

**Comment by MichaelOstling** [comment]
DCAT-AP är en Europeisk profil  och ämnat för Europiska portaler.
En profil är normalt framtagen för att underlätta och minska antalet val så därför pekar man specifikt ut denna värdelist med bara officiella Europeiska Språk. Dock kan man tänka sig att då man vill beskriva språk i data att denna lista kan vara vidare med språk som Nord-syd samiska. 

Men frågan är intressant ur interoperabilitets synpunkt.

**Comment by matthiaspalmer** [comment]
Jag tror det är olämpligt att avvika från den lista som är framtagen av publication office. Därför markerar jag denna som att den inte ska åtgärdas.
