### ISSUE TITLE
Hur översätter vi dcterms:creator till svenska

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#35]
I och med DCAT-AP2 kommer dcterms:creator att läggas till explicit.
Specen säger:
"This property refers to the entity primarily responsible for producing the dataset"
Och DCAT2 säger lite mer allmänt då de introducerar dcterms:creator oavsett dcat:Dataset:
"The entity responsible for producing the resource."

Vad ska vi kalla den på svenska:

- skapare
- upphovsman
- kreatör
- producent

Man kan ta inspiration av de som tillhandahålls av INSPIRE:
[http://inspire.ec.europa.eu/metadata-codelist/ResponsiblePartyRole/](http://inspire.ec.europa.eu/metadata-codelist/ResponsiblePartyRole/)
Välj svenska högst upp på sidan för att se de översättningar som finns där.

**Comment by mattiasekhem** [comment]
Jag röstar på Skapare. Termen upphovsman heter author i INSPIRE och både producent och kreatör kan leda åt andra håll.

**Comment by MatsAhlin** [comment]
Jag vet att vi tidigare har haft problem från Svenska Kyrkan när det användes Skapare.

**Comment by matthiaspalmer** [comment]
Vad jag kan minnas röstade möte 2 för producent. Åtgärdat och stängs nu.

**Comment by peterk** [comment]
Missa inte den översättning som KB gjorde tidigare där flera Dublin Core-element finns översatta till svenska: https://web.archive.org/web/20070606223847/http://www.kb.se/Metadata/dcmes/20060130.htm

**Comment by bjornhagstrom** [comment]
@peterk, använder KB det aktivt i verksamheten eller blev det en pappersprodukt? Vet du om andra använder det?

**Comment by peterk** [comment]
Det är den översättning som Dublin Core-organisationen pekar på i listan av översättningar: https://www.dublincore.org/resources/translations/

Rätt säker på att den översättningen använts i t.ex. design av system  som hanterar data där DC-element använts.
