### ISSUE TITLE
Hur översätter vi dcat:DataService

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#36]
Förslag:

- Tjänst
- Datatjänst

Argument för "Datatjänst" är att vi i ett senare skede vill kunna särskilja mellan tjänster som är enbart för att hämta ut information (då datatjänst) och de som är till för att lämna in eller ändra information (förslagsvis bara tjänst).
Exempel på den sedemera skulle kunna vara "deklarera hos skatteverket".

**Comment by bjornhagstrom** [comment]
Förslaget är nog bra men jag ser inte att det finns något inbyggt i namnet som innebär att det är envägskommunikation och inte tvåvägskommunikation.

**Comment by matthiaspalmer** [comment]
Sant. Egentligen finns flera dimensioner som vore bra att kunna skilja på:

- digital / icke digital (t.ex. deklarera online vs. skicka via vanlig post)
- Data kan läsas / skrivas  
- Data kan accessas / transformeras (t.ex. valutaöversättning transformerar bara, ingen access)

Jag menar att med Dataservice menar vi tjänster som är digitala, läs och accessorienterade.
Men då det finns för många kombinationer för att antyda alla i namnet, tror vi snarare behöver ett namn nu som vi kan definiera tydligare i ett senare skede om det behövs.

**Comment by bjornhagstrom** [comment]
Ja det tror jag är en bra approach. Bra om det är tydligt också.

**Comment by thomaskvist** [comment]
För mig skulle dataservice fungera. I svensk ordbok står följande: 

Service =
upp­sättning tjänster som ställs till förfogande på visst om­råde; vanligen av före­tag el. organisation, för all­mänheten, kund­kretsen etc.

**Comment by matthiaspalmer** [comment]
Vad jag minns beslöt möte 2 att använda datatjänst.
