### ISSUE TITLE
Vad kallar vi temporal resolution

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#38]
En ny egenskap heter dcat:temporalResolution och pekar på en xsd:duration.

Jag har bara ett föreslag:

-  tidsupplösning

**Comment by bjornhagstrom** [comment]
Kommer inte på något bättre men jag är heller inte säker på vad den ska betyda?

**Comment by thomaskvist** [comment]
Förstår logiken men kan inte komma på något annat alternativ än tidsgranularitet  vilket inte känns särskilt bra.  Tidsupplösning känns bättre. Däremot tror jag att man ska återanvända det ord man bestämmer sig för att beskriva hur finfördelat datat är, t ex "geografisk upplösning" om det nu tillkommer i DCAT-AP (finns kanske för geodata?) så att det blir en logik i benämningarna.

**Comment by matthiaspalmer** [comment]
Tidsupplösning blir det.
