### ISSUE TITLE
Vad kallar vi endpoint

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#39]
Två nya properties är dcat:endpointURL och dcat:endpointDescription.
För det behovet behöver vi tala om endpoints, dvs hur man kommer åt en webbservice.
På engelska kallas det helt enkelt endpoint, här kommer några förslag på svenska:

- Slutpunkt
- Ingångsadress
- Åtkomstadress - denna har jag valt för tillfället
- Åtkomstpunkt
- Startpunkt

Fler förslag?

**Comment by bjornhagstrom** [comment]
Det eller Åtkomstadress men jag föredrar ditt val.

**Comment by matthiaspalmer** [comment]
Åtkomstadress blir det.
