### ISSUE TITLE
3 Applikationsprofiler och underpunkter

### ISSUE THREAD

**Issue by bjornhagstrom** [MetaSolutionsAB/DCAT-AP-SE#40]
Alla dessa behöver human readable förklaringar och definitioner. Jag kan själv inte riktigt förklara skillnaderna mellan datatjänst och distribution till exempel. Jag funderar också på om 3.1-3.4 inte ska vara i någon sorts logisk hierarkisk ordning med katalog först?

**Comment by matthiaspalmer** [comment]
Ordningen i metadataspecifikationen är nu:
1. Katalog
2. Datamängd
3. Distribution
4. Datatjänst
5. Aktör
6. Kontaktuppgift

Försöker klämma in en föklarande text kring de olika klasserna i dokumentationen också.
