### ISSUE TITLE
Obligatorisk licens för katalogen

### ISSUE THREAD

**Issue by matthiaspalmer** [MetaSolutionsAB/DCAT-AP-SE#5]
DCAT-AP säger att en licens är rekommenderad för katalogen.
Riksarkivets föreslår att en licens är obligatorisk.
Observera att licensen som anges för katalogen bara gäller metadatan om datamängderna, inte datamängderna själva. Licensen för datamängderna måste anges separat på distributionsnivån.

Effekten av att ange licens på katalogen blir därmed inte så stor. I princip skulle man kunna argumentera att eftersom PSI-lagen kräver att man ska leverera en PSI förteckning digitalt och utan avgift så finns inte så stort uttrymme att välja licenser. Det är också ytterst olämpligt att välja en licens som CC-BY då det skulle ställa till det för öppnadata.se som aggregerar informationen.

Fokus på licens på katalog kan leda till att man missförstår och inte uttrycker den mycket viktigare på distributionsnivån.

**Comment by kristineulander** [comment]
Håller med

**Comment by bjornhagstrom** [comment]
Den som publicerar metadata måste alltså gå med på en licens för att kunna mata in metadata? Jag tycker det är rimligt att ha CC0 som villkor för det för enklare hantering. Går man inte med på det så bör man nog inte använda katalogen.

Hur detta presenteras i inmatningsgränssnittet är viktigt så man fattar vad man lovar och inte.

**Comment by matekh** [comment]
Det bör alltså vara obligatoriskt värde CC0 på katalognivå!

**Comment by thomaskvist** [comment]
Har för mig att jag för länge sedan hörde att allmänna offentliga handlingar ska vara Public Domain vilket väl inte är identiskt med CC0. Nu var detta länge sedan och jag kan minnas fel/bedömningen kan ha ändrats. Har för mig att du @bjornhagstrom var med då någon av SKL inhyrd jurist nämnde detta. Har du eller någon annan koll på relationen Public Domain och CC0 och om det finns begränsningar i möjligheten att kräva användandet av CC0 eller mer restriktiva licenser för allmänna offentliga handlingar?
